
# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  #azureSubscription: 'e1acc1c4-a6cb-41d0-b98c-92a6f092bd71'

  # Web app name
  webAppName: 'shinelabjava'

  # Environment name
  environmentName: 'shinelabjava'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: ANT Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Ant@1
      inputs:
        workingDirectory: ''
        buildFile: 'build.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*/*.?(war|jar)'
        #$(System.DefaultWorkingDirectory)/**/*.jar
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop
     

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'shine-lab(61ff743f-b913-4634-8b9a-200c86c1d4aa)'
        appType: 'webApp'
        WebAppName: 'shinelabjava'
        packageForLinux: '$(System.DefaultWorkingDirectory)/drop/build/*jar'




